server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create

  datasource:
    username: daou
    password: daou2020!
    url: jdbc:mariadb://daou-it-maria.cy9pjdfbrh5z.ap-northeast-2.rds.amazonaws.com:3306/daou
    driver-class-name: org.mariadb.jdbc.Driver